AI attacked location (1,6) and missed
AI attacked location (7,0) and missed
AI attacked location (0,7) and missed
AI attacked location (3,3) and hit
AI attacked location (0,3) and missed
AI attacked location (0,0) and missed
AI attacked location (5,8) and missed
AI attacked location (3,2) and missed
AI attacked location (3,4) and missed
AI attacked location (4,0) and missed
AI attacked location (8,3) and hit
AI attacked location (0,5) and missed
AI attacked location (1,4) and missed
AI attacked location (8,0) and missed
AI attacked location (3,6) and hit
AI attacked location (6,0) and missed
AI attacked location (4,0) and missed
AI attacked location (4,2) and missed
AI attacked location (4,2) and missed
AI attacked location (3,4) and missed
AI attacked location (5,7) and missed
AI attacked location (2,4) and missed
AI attacked location (9,9) and missed
AI attacked location (0,8) and missed
AI attacked location (3,0) and missed
AI attacked location (6,2) and missed
AI attacked location (5,1) and hit
AI attacked location (1,6) and missed
AI attacked location (6,9) and hit
AI attacked location (5,6) and hit
AI attacked location (1,9) and missed
AI attacked location (9,3) and hit
AI attacked location (3,7) and missed
AI attacked location (1,2) and missed
AI attacked location (0,1) and missed
AI attacked location (0,2) and missed
AI attacked location (6,0) and missed
AI attacked location (0,4) and missed
AI attacked location (7,8) and missed
AI attacked location (6,4) and missed
AI attacked location (5,4) and missed
AI attacked location (9,5) and missed
AI attacked location (9,3) and hit
AI attacked location (1,0) and missed
AI attacked location (0,4) and missed
AI attacked location (8,0) and missed
AI attacked location (9,6) and missed
AI attacked location (6,8) and missed
AI attacked location (3,3) and hit
AI attacked location (8,0) and missed
AI attacked location (3,8) and missed
AI attacked location (7,4) and missed
AI attacked location (4,0) and missed
AI attacked location (6,3) and missed
AI attacked location (6,2) and missed
AI attacked location (6,3) and missed
AI attacked location (4,2) and missed
AI attacked location (7,1) and missed
AI attacked location (2,0) and missed
AI attacked location (5,5) and missed
AI attacked location (6,9) and hit
AI attacked location (4,3) and missed
AI attacked location (3,7) and missed
AI attacked location (9,2) and missed
AI attacked location (9,6) and missed
AI attacked location (1,1) and missed
AI attacked location (4,9) and missed
AI attacked location (0,5) and missed
AI attacked location (0,1) and missed
AI attacked location (7,0) and missed
AI attacked location (6,3) and missed
AI attacked location (9,5) and missed
AI attacked location (7,0) and missed
AI attacked location (8,9) and hit
AI attacked location (2,7) and missed
AI attacked location (1,0) and missed
AI attacked location (3,5) and missed
AI attacked location (2,5) and missed
AI attacked location (7,9) and hit
AI attacked location (4,4) and missed
AI attacked location (7,9) and hit
AI attacked location (7,2) and missed
AI attacked location (3,8) and missed
AI attacked location (7,4) and missed
AI attacked location (2,5) and missed
AI attacked location (7,3) and missed
AI attacked location (7,9) and hit
AI attacked location (8,2) and missed
AI attacked location (7,5) and missed
AI attacked location (0,3) and missed
AI attacked location (7,1) and missed
AI attacked location (2,6) and missed
AI attacked location (1,6) and missed
AI attacked location (9,1) and missed
AI attacked location (2,5) and missed
AI attacked location (1,6) and missed
AI attacked location (6,6) and hit
AI attacked location (4,2) and missed
AI attacked location (1,0) and missed